name: Update Medium posts

on:
  schedule:
    - cron: "0 */12 * * *"   # Atualiza 2x por dia
  workflow_dispatch:

jobs:
  update-medium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Medium posts section
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@debs.dezotti"
          max_post_count: 3
          comment_tag_name: "MEDIUM-LATEST-POSTS"
          disable_html_encoding: true
          title_max_length: 80
          description_max_length: 140
          template: |
              <a href="$url" target="_blank" style="text-decoration: none; color: inherit;">
                <div style="
                  background: #f7f9fc;
                  border-radius: 16px;
                  padding: 16px;
                  width: 240px;
                  height: 160px;
                  display: flex;
                  flex-direction: column;
                  justify-content: space-between;
                  box-shadow: 0 2px 8px rgba(0,0,0,0.06);
                  transition: transform 0.15s ease;
                ">
                  <div style="font-size: 28px;">✍️</div>
                  <div style="font-weight: 600; font-size: 14px; color: #1a1a1a; line-height: 1.3;">
                    $title
                  </div>
                  <div style="font-size: 12px; color: #6b6b6b;">
                    $date
                  </div>
                </div>
              </a>
              $newline


      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Medium posts"
